// app/legal/licenses.js
// Third-party licence notices.
//
// The bundled JSON is generated by scripts/build-licenses.cjs from the
// installed production dependency tree. Keeping the notices inside the app is
// what satisfies the attribution requirements of the MIT, BSD, Apache, and
// SIL Open Font licences; the hosted Licences page is a convenience, not the
// distribution.

import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useCallback, useContext, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import licences from "../../assets/legal/licenses.json";
import { GlobalContext } from "../../context/GlobalContext";

function LicenceRow({ item, expanded, onToggle, theme, fontSize, t }) {
  const hasText = Boolean(item.text);

  return (
    <Pressable
      onPress={hasText ? onToggle : undefined}
      accessibilityRole={hasText ? "button" : undefined}
      accessibilityState={hasText ? { expanded } : undefined}
      accessibilityLabel={
        hasText ? t("licenses.toggleA11y", { name: item.name }) : undefined
      }
      style={[
        styles.card,
        { backgroundColor: theme.card, borderColor: theme.border },
      ]}
    >
      <View style={styles.cardHeader}>
        <View style={styles.cardTitle}>
          <Text
            style={[styles.name, { color: theme.textPrimary, fontSize }]}
          >
            {item.name}
          </Text>
          {item.version ? (
            <Text
              style={[
                styles.version,
                { color: theme.textSecondary, fontSize: Math.max(11, fontSize - 3) },
              ]}
            >
              {item.version}
            </Text>
          ) : null}
        </View>
        {hasText ? (
          <Ionicons
            name={expanded ? "chevron-up" : "chevron-down"}
            size={Math.max(16, fontSize)}
            color={theme.textSecondary}
          />
        ) : null}
      </View>

      <Text
        style={[
          styles.license,
          { color: theme.accent, fontSize: Math.max(11, fontSize - 3) },
        ]}
      >
        {item.license}
      </Text>

      {expanded && hasText ? (
        <Text
          style={[
            styles.licenseText,
            { color: theme.textSecondary, fontSize: Math.max(10, fontSize - 4) },
          ]}
        >
          {item.text}
        </Text>
      ) : hasText ? (
        <Text
          style={[
            styles.hint,
            { color: theme.textPlaceholder, fontSize: Math.max(10, fontSize - 4) },
          ]}
        >
          {t("licenses.tapToRead")}
        </Text>
      ) : null}
    </Pressable>
  );
}

export default function LicencesScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const { theme, settings } = useContext(GlobalContext);
  const fontSize = settings?.ux?.fontSize || 16;
  const [expandedNames, setExpandedNames] = useState(() => new Set());

  const packages = useMemo(() => licences?.packages || [], []);

  const goBack = useCallback(() => {
    if (router.canGoBack?.()) router.back();
    else router.replace("/(tabs)/settings");
  }, [router]);

  const toggle = useCallback((name) => {
    setExpandedNames((prev) => {
      const next = new Set(prev);
      if (next.has(name)) next.delete(name);
      else next.add(name);
      return next;
    });
  }, []);

  const renderItem = useCallback(
    ({ item }) => (
      <LicenceRow
        item={item}
        expanded={expandedNames.has(item.name)}
        onToggle={() => toggle(item.name)}
        theme={theme}
        fontSize={fontSize}
        t={t}
      />
    ),
    [expandedNames, fontSize, t, theme, toggle]
  );

  return (
    <SafeAreaView
      style={[styles.safe, { backgroundColor: theme.background }]}
      edges={["top"]}
    >
      <View
        style={[
          styles.header,
          { borderBottomColor: theme.border, backgroundColor: theme.card },
        ]}
      >
        <Pressable
          onPress={goBack}
          accessibilityRole="button"
          accessibilityLabel={t("common.back")}
          style={styles.backButton}
        >
          <Ionicons
            name="chevron-back"
            size={Math.max(20, fontSize + 4)}
            color={theme.accent}
          />
        </Pressable>
        <Text
          style={[styles.title, { color: theme.textPrimary, fontSize: fontSize + 4 }]}
        >
          {t("licenses.title")}
        </Text>
        <View style={styles.backButton} />
      </View>

      <FlatList
        data={packages}
        keyExtractor={(item) => `${item.name}@${item.version}`}
        renderItem={renderItem}
        initialNumToRender={12}
        windowSize={7}
        contentContainerStyle={styles.listContent}
        ListHeaderComponent={
          <View style={styles.intro}>
            <Text
              style={[
                styles.introText,
                { color: theme.textSecondary, fontSize: Math.max(12, fontSize - 2) },
              ]}
            >
              {t("licenses.intro")}
            </Text>
          </View>
        }
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    flex: 1,
    textAlign: "center",
    fontWeight: "800",
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 40,
  },
  intro: {
    marginBottom: 12,
  },
  introText: {
    lineHeight: 19,
  },
  card: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  cardTitle: {
    flex: 1,
  },
  name: {
    fontWeight: "700",
  },
  version: {
    marginTop: 2,
  },
  license: {
    marginTop: 6,
    fontWeight: "600",
  },
  licenseText: {
    marginTop: 10,
    lineHeight: 16,
  },
  hint: {
    marginTop: 8,
    fontStyle: "italic",
  },
});
